# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# 代码生成
gen:
  # 作者
  author: ruoyi
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.system
  # 自动去除表前缀，默认是false
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

# MyBatis配置
mybatis:
  # 搜索指定包别名
#  typeAliasesPackage: com.generator.domain
  typeAliasesPackage: com.**.domain
  #配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:/mapper/*Mapper.xml
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql